-- AlterTable
ALTER TABLE "Channel" ADD COLUMN     "feeRate" DECIMAL(5,4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "actualPayout" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "fixedFee" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isSettled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "paymentFee" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "platformSubsidy" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "serviceFee" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "settledAt" TIMESTAMP(3);
